export const URL_AUTHENTICATE = "https://www.bahatech.cl:8443/baha_games_marketplace/authenticate"
export const URL_REGISTRAR_USUARIO = "https://www.bahatech.cl:8443/baha_games_marketplace/usuarios/agregarUsuario"
export const URL_OBTENER_INFO_GEOGRAFICA = "https://btl7.github.io/resources/data/regiones-comunas.json"
export const URL_BUSCAR_USUARIO_LOGIN = "https://www.bahatech.cl:8443/baha_games_marketplace/usuario/"
export const URL_MODIFICAR_USUARIO = "https://www.bahatech.cl:8443/baha_games_marketplace/usuario/modificar"
export const URL_MODIFICAR_CREDENCIALES = "https://www.bahatech.cl:8443/baha_games_marketplace/udata/modificar"
export const URL_BUSCAR_USUARIO_ID = "https://www.bahatech.cl:8443/baha_games_marketplace/usuariof/"